// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZV_NrOGRqAzOgvXI5gF3vpBmYVGHYnHU',
    appId: '1:150680960224:web:8dfd5b18b9c3b338cc2485',
    messagingSenderId: '150680960224',
    projectId: 'shohozkotha',
    authDomain: 'shohozkotha.firebaseapp.com',
    storageBucket: 'shohozkotha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHcDI7Mz0N1eaBnJPZhFHg1BC8k6erJv4',
    appId: '1:150680960224:android:73b8926087d98ec6cc2485',
    messagingSenderId: '150680960224',
    projectId: 'shohozkotha',
    storageBucket: 'shohozkotha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbnVqsKq4zeNJDon7HsG0nPmZQE0sV48',
    appId: '1:150680960224:ios:b533ae345946c67dcc2485',
    messagingSenderId: '150680960224',
    projectId: 'shohozkotha',
    storageBucket: 'shohozkotha.appspot.com',
    iosBundleId: 'com.example.shohojKotha2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbnVqsKq4zeNJDon7HsG0nPmZQE0sV48',
    appId: '1:150680960224:ios:86a9b61cd1d42f92cc2485',
    messagingSenderId: '150680960224',
    projectId: 'shohozkotha',
    storageBucket: 'shohozkotha.appspot.com',
    iosBundleId: 'com.example.shohojKotha2.RunnerTests',
  );
}
